"""Add rich project details

Revision ID: 09749191e914
Revises: 4728c2fe588d
Create Date: 2025-09-03 21:26:34.343537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09749191e914'
down_revision = '4728c2fe588d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_goals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tech_stack', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_criteria', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('resources')
        batch_op.drop_column('evaluation_criteria')
        batch_op.drop_column('tech_stack')
        batch_op.drop_column('project_goals')

    # ### end Alembic commands ###
