"""adding work_model

Revision ID: 13e6451a9185
Revises: 3ce3a7f3d260
Create Date: 2025-09-16 20:28:53.519713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e6451a9185'
down_revision = '3ce3a7f3d260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_column('work_model')

    # ### end Alembic commands ###
