"""Adding is_edited

Revision ID: 1ad420a63833
Revises: fb840cfba7cf
Create Date: 2025-09-19 10:48:47.387994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad420a63833'
down_revision = 'fb840cfba7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        # --- PERBAIKAN DI BARIS INI ---
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=False, server_default='0'))
        # --- AKHIR PERBAIKAN ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###