"""Adds lesson_id to ChatSession model

Revision ID: 1ba5000dc0ea
Revises: e39ddd8efca8 
Create Date: 2025-09-13 14:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba5000dc0ea'
down_revision = 'e39ddd8efca8' # Pastikan ini adalah ID revisi sebelumnya
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        # --- PERBAIKAN DI SINI ---
        # Memberi nama eksplisit pada foreign key constraint
        batch_op.create_foreign_key(
            'fk_chat_session_lesson_id_lesson', # Nama constraint baru
            'lesson', ['lesson_id'], ['id']
        )
        # --- AKHIR PERBAIKAN ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        # --- PERBAIKAN DI SINI ---
        # Menggunakan nama yang sama untuk menghapus constraint
        batch_op.drop_constraint('fk_chat_session_lesson_id_lesson', type_='foreignkey')
        # --- AKHIR PERBAIKAN ---
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###