"""Link projects to study groups

Revision ID: 1c806c2154a1
Revises: 1f007f7a6dae
Create Date: 2025-09-20 06:54:19.447718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c806c2154a1'
down_revision = '1f007f7a6dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_study_group')
    op.drop_table('_alembic_tmp_direct_message')
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['current_project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_project_id')

    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    op.create_table('_alembic_tmp_direct_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_study_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('current_project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['current_project_id'], ['project.id'], name=op.f('fk_study_group_current_project_id_project')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
