"""Add xp and level to User model

Revision ID: 209931c39342
Revises: 2c8e710ee5de
Create Date: 2025-09-17 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209931c39342'
down_revision = '2c8e710ee5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # PERBAIKAN: Tambahkan server_default='0' dan server_default='1'
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###