"""Add unique constraint to JobApplication

Revision ID: 2c8e710ee5de
Revises: 13e6451a9185
Create Date: 2025-09-16 21:35:15.729752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8e710ee5de'
down_revision = '13e6451a9185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_company_position_uc', ['user_id', 'company_name', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_constraint('_user_company_position_uc', type_='unique')

    # ### end Alembic commands ###
