"""Add generated_cv_json to UserResume

Revision ID: 2f0358c38291
Revises: 1550ba2440c9
Create Date: 2025-09-11 11:52:15.396664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0358c38291'
down_revision = '1550ba2440c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_cv_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_resume', schema=None) as batch_op:
        batch_op.drop_column('generated_cv_json')

    # ### end Alembic commands ###
