"""Add cooldown_until to QuizHistory

Revision ID: 3443c85bf01d
Revises: 0adb74ea445f
Create Date: 2025-09-15 21:00:31.702528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3443c85bf01d'
down_revision = '0adb74ea445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooldown_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.drop_column('cooldown_until')

    # ### end Alembic commands ###
