"""Add career_path to Certificate model

Revision ID: 3ce3a7f3d260
Revises: e4b9920fd921
Create Date: 2025-09-16 08:44:48.590862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce3a7f3d260'
down_revision = 'e4b9920fd921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('career_path')

    # ### end Alembic commands ###
