"""Add privacy setting to study groups

Revision ID: 48cca0b1e5da
Revises: 18625893992c
Create Date: 2025-09-13 21:29:19.608816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cca0b1e5da'
down_revision = '18625893992c'
branch_labels = None
depends_on = None


# Di dalam file 48cca0b1e5da_....py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        # TAMBAHKAN server_default='0' DI SINI
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default='0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
