"""Add content field to Lesson model

Revision ID: 54878714f208
Revises: 8031f3f59fdc
Create Date: 2025-09-12 18:28:27.355661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54878714f208'
down_revision = '8031f3f59fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
