"""Add community and connection models

Revision ID: 55f3d4692ce3
Revises: 9f8551f1a0fc
Create Date: 2025-09-13 19:57:16.455575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f3d4692ce3'
down_revision = '9f8551f1a0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_request_timestamp'), ['timestamp'], unique=False)

    op.create_table('connections',
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_a_id', 'user_b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_request_timestamp'))

    op.drop_table('connection_request')
    # ### end Alembic commands ###
