"""Add description to Lesson model

Revision ID: 683dc3f2638e
Revises: d549f5d3d76f
Create Date: 2025-09-08 15:23:57.454620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683dc3f2638e'
down_revision = 'd549f5d3d76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
