"""Remove code editor feature

Revision ID: 6b444d3ec40e
Revises: d01137000753
Create Date: 2025-09-04 16:11:27.484428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b444d3ec40e'
down_revision = 'd01137000753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_file')
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_session_timestamp'))

    op.drop_table('coding_session')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('coding_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_session_timestamp'), ['timestamp'], unique=False)

    op.create_table('code_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_folder', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['code_file.id'], name=op.f('fk_code_file_parent_id_code_file')),
    sa.ForeignKeyConstraint(['session_id'], ['coding_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
