"""Add JobApplication model

Revision ID: 7465fc80ada1
Revises: 2f0358c38291
Create Date: 2025-09-11 20:01:33.795287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7465fc80ada1'
down_revision = '2f0358c38291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('job_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['user_resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application')
    # ### end Alembic commands ###
