"""Add video_url to Lesson model

Revision ID: 762a06460fa5
Revises: 54878714f208
Create Date: 2025-09-12 19:30:54.711628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762a06460fa5'
down_revision = '54878714f208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
