"""Add generated_content to Project model

Revision ID: 7c4b7594b7b9
Revises: a4bff57d49d8
Create Date: 2025-09-18 14:09:09.262375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4b7594b7b9'
down_revision = 'a4bff57d49d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_content', sa.Text(), nullable=True))

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_completed_at'), ['completed_at'], unique=False)
        batch_op.drop_column('first_completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_completed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_progress_completed_at'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('generated_content')

    # ### end Alembic commands ###
