"""Add content to Lesson model

Revision ID: 878240db117f
Revises: 762a06460fa5
Create Date: 2025-09-13 09:00:32.320320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878240db117f'
down_revision = '762a06460fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
