"""Add Certificate model

Revision ID: 95966fb0fd6f
Revises: 2633a3d5e6f2
Create Date: 2025-09-16 07:43:09.687538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95966fb0fd6f'
down_revision = '2633a3d5e6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('projects_completed_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    # ### end Alembic commands ###
