"""Add description and video_url to Lesson

Revision ID: 987177a87901
Revises: a678472be164
Create Date: 2025-09-03 08:58:40.712887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987177a87901'
down_revision = 'a678472be164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
