"""Add JobMatchAnalysis model

Revision ID: 9f8551f1a0fc
Revises: 1ba5000dc0ea
Create Date: 2025-09-13 15:06:38.751563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8551f1a0fc'
down_revision = '1ba5000dc0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_match_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('match_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_resume_id'], ['user_resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_match_analysis')
    # ### end Alembic commands ###
