"""add_completion_status_to_userprogress

Revision ID: a4bff57d49d8
Revises: 209931c39342
Create Date: 2025-09-18 08:54:33.963039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bff57d49d8'
down_revision = '209931c39342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_progress_completed_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_completed_at'), ['completed_at'], unique=False)
        batch_op.drop_column('first_completed_at')

    # ### end Alembic commands ###
