"""Add username column to user table

Revision ID: b03a2ca59af5
Revises: 55f3d4692ce3
Create Date: 2025-09-13 20:07:29.401551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03a2ca59af5'
down_revision = '55f3d4692ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        # UBAH BARIS DI ATAS MENJADI SEPERTI INI:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])


    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # PASTIKAN ANDA JUGA MENGEDIT BAGIAN INI
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
