"""Resync SKS fields try 3

Revision ID: bca1f75fad3d
Revises: 3dd255b3b816
Create Date: 2026-01-24 15:11:28.757441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca1f75fad3d'
down_revision = '3dd255b3b816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_coding', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_predicted_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('ai_predicted_duration')
        batch_op.drop_column('is_coding')
        batch_op.drop_column('estimated_pages')

    # ### end Alembic commands ###
