"""Add StudyGroup and GroupChatMessage models

Revision ID: bce4890cf359
Revises: 48cca0b1e5da
Create Date: 2025-09-14 09:04:05.908298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce4890cf359'
down_revision = '0d4ebca6f5d2' # Pastikan ini adalah ID revisi sebelumnya yang benar
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('career_path', sa.String(length=100), nullable=True))
        # PERBAIKAN: Beri nama pada constraint yang akan dihapus
        batch_op.drop_constraint('fk_study_group_creator_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_study_group_owner_id_user'), 'user', ['owner_id'], ['id'])
        batch_op.drop_column('creator_id')
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_study_group_owner_id_user'), type_='foreignkey')
        # PERBAIKAN: Beri nama pada constraint yang akan dibuat kembali
        batch_op.create_foreign_key('fk_study_group_creator_id_user', 'user', ['creator_id'], ['id'])
        batch_op.drop_column('career_path')
        batch_op.drop_column('owner_id')

    op.drop_table('group_chat_message')
    # ### end Alembic commands ###