"""Add UserActivityLog model

Revision ID: c231cef45066
Revises: 3443c85bf01d
Create Date: 2025-09-15 21:42:49.659929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c231cef45066'
down_revision = '3443c85bf01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('notification_minutes_before')
        batch_op.drop_column('enable_notifications')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('notification_minutes_before')
        batch_op.drop_column('enable_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('notification_minutes_before', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('notification_minutes_before', sa.INTEGER(), nullable=True))

    op.drop_table('user_activity_log')
    # ### end Alembic commands ###
