"""Add reflection to UserProject

Revision ID: cab1536c1efe
Revises: be61971a21bd
Create Date: 2025-09-09 21:45:31.330668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab1536c1efe'
down_revision = 'be61971a21bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflection', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.drop_column('reflection')

    # ### end Alembic commands ###
