"""Add reminder_minutes to Event and Task

Revision ID: cba10c77e8c3
Revises: 683dc3f2638e
Create Date: 2025-09-08 19:13:29.781093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba10c77e8c3'
down_revision = '683dc3f2638e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_minutes')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('reminder_minutes')

    # ### end Alembic commands ###
