"""Link project to chat session

Revision ID: ce52682b8990
Revises: 7b7a259b7741
Create Date: 2025-09-03 12:40:34.722964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce52682b8990'
down_revision = '7b7a259b7741'
branch_labels = None
depends_on = None


# migrations/versions/ce52682b8990_....py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_session_id', sa.Integer(), nullable=True))
        # Berikan nama constraint di parameter pertama
        batch_op.create_foreign_key('fk_project_chat_session_id', 'chat_session', ['chat_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_session_id')

    # ### end Alembic commands ###
