"""Add CodingSession model and folder support

Revision ID: d01137000753
Revises: 418e1433ae72
Create Date: 2025-09-04 14:39:25.326277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01137000753'
down_revision = '418e1433ae72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_file', schema=None) as batch_op:
        # Di dalam with op.batch_alter_table(...):
        batch_op.add_column(sa.Column('is_folder', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_code_file_timestamp'))
        # Di dalam with op.batch_alter_table(...):
        batch_op.create_foreign_key('fk_code_file_parent_id_code_file', 'code_file', ['parent_id'], ['id'])
        batch_op.drop_column('language')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('code_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_code_file_timestamp'), ['timestamp'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('parent_id')
        batch_op.drop_column('is_folder')

    # ### end Alembic commands ###
