"""empty message

Revision ID: d549f5d3d76f
Revises: c4c6dd32b78a
Create Date: 2025-09-07 19:39:55.991926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd549f5d3d76f'
down_revision = 'c4c6dd32b78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('notification_minutes_before', sa.Integer(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('notification_minutes_before', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('notification_minutes_before')
        batch_op.drop_column('enable_notifications')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('notification_minutes_before')
        batch_op.drop_column('enable_notifications')

    # ### end Alembic commands ###
