"""Add quiz history to UserProgress

Revision ID: f9ddc9dc441c
Revises: e425bea434d8
Create Date: 2025-09-15 08:34:33.385836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ddc9dc441c'
down_revision = 'e425bea434d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('quiz_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
